title: "[ADO IDEA]: " # Users will complete the title
labels: ["ado-idea", "proposal"] # Optional: add labels automatically
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to propose a new ADO! Please fill out the details below.
  - type: textarea
    id: problem-solved
    attributes:
      label: "1. What is the core problem your ADO solves?"
      description: "A clear and concise description of the problem or need."
      placeholder: "e.g., Users need a way to securely time-lock tokens for vesting schedules."
    validations:
      required: true
  - type: textarea
    id: ado-description
    attributes:
      label: "2. Describe your proposed ADO."
      description: "What does it do? What are its key features and functionalities?"
      placeholder: "e.g., A smart contract that allows users to deposit tokens which are then released incrementally to a beneficiary based on a predefined schedule..."
    validations:
      required: true
  - type: input
    id: target-user
    attributes:
      label: "3. Who is the target user for this ADO?"
      description: "e.g., dApp developers, DAO treasuries, individual token holders"
      placeholder: "Specify the primary users"
    validations:
      required: true
  - type: textarea
    id: benefits-impact
    attributes:
      label: "4. What are the potential benefits or impact of this ADO?"
      description: "How would it improve the Andromeda ecosystem or user experience?"
    validations:
      required: true
  - type: textarea
    id: similar-concepts
    attributes:
      label: "5. Are there any similar existing ADOs or concepts (on Andromeda or other platforms)?"
      description: "If so, how is your idea different or better?"
      placeholder: "e.g., Similar to X, but offers Y improvement..."
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Add any other context, diagrams, mockups, or relevant links here."
    validations:
      required: false